[package]
name = "power-4"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "power-4"
path = "src/main.rs"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.29.0"
ratatui = "0.30.0"

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true